### PR TITLE
Chapter Four Example by Noah Wamble

### PR DESCRIPTION
**Pull request by noahwamble**
Created example for Chapter 4 using the ADR equation

### CODE REVIEW

**Review by adowling2 — CHANGES_REQUESTED** [review]
These look good. I gave the notebook a more descriptive title, updated the file name, and fixed a minor execution order bug.

Did this example come from Prof. McClarren or the textbook. If so, just post here a sentence you would like to add to cite/acknowledge the source.

**Comment by noahwamble** [comment]
Yes, this example came straight out of the textbook, and the code was adapted from the chapter 4 supplemental material. I can add a citation to the bottom if you like!

**Comment by adowling2** [comment]
Just add the 1 or 2 sentence acknowledgment/citation here. I'll incorporate it into the notebook. (I modified the notebook, so this will be easiest. Otherwise, you'll need to redownload the file.)

**Comment by noahwamble** [comment]
Works Cited 

Code adapted from chapter 4 supplemental material.
McClarren, Ryan G. _Uncertainty Quantification and Predictive Computational Science: a Foundation for Physical Scientists and Engineers_. Springer, 2018.

**Pull request merged**
