### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cvillas2**

### CODE REVIEW

**Comment by cvillas2** [comment]
Completed example 02.01.

**Comment by adowling2** [comment]
@cvillas2 This looks good. I fixed one minor typo in the notebook.

Where did the three figures come from? Tacq, J. (2010)? If so, please explicitly cite these after each figure. For example, write "Figure X in Tacq (2010)". Also, please save the figures as a .png file and add to /figures.

**Comment by cvillas2** [comment]
Updated figures and references

**Review by adowling2 — APPROVED** [review]
Looks good.

**Pull request merged**
